name: CI
on: push
jobs:
  linter-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --output-format=github .

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install "poetry==2.2.0"
      - name: Install dependencies
        run: |
          poetry add pytest-github-actions-annotate-failures
          poetry install --no-root
      - name: Run pytest
        run: poetry run pytest
