name: Python Lint

on:
    push:
        branches: [ "develop" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:


jobs:
    lint:
        permissions:
            contents: read
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: Install Poetry
              run: pipx install poetry

            - name: Poetry add
              run: poetry add ruff

            - name: Install dependencies
              run: poetry install --no-interaction --no-root

            - name: Lint
              run: |
                poetry run ruff check ./api --output-format=github .