name: Python Lint

on:
    push:
        branches: [ "develop" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: Format and Commit
              uses: astral-sh/ruff-action@v3
              with:
                args: "format --check --diff"